trigger: none

pr: none

variables:
- name: devEnvironment
  value: dev
# TODO: provide an email address for the ExampleWorkflow to an send mail to
- name: toEmailAddress
  value: 'prakash.beegala@microsoft.com'

resources:
  pipelines:
  - pipeline: cilogicapp
    # TODO: Update with the name of your CI pipeline
    source: 'prbeegala.logicappsaa'
    trigger:
      branches:
      - main

stages:
- stage: DEV
  displayName: 'DEV Deployment'
  variables:
  - template: variables/pipeline-vars.yml
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-18.04
    environment: $(devEnvironment)
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: 'BeegalaInternalSubscription'
              appType: 'functionapp,workflowapp'
              appName: '$(logicAppName)'
              package: '$(Pipeline.Workspace)/cipipeline/$(logicAppCIArtifactName)/$(resources.pipeline.cipipeline.runID).zip'
              appSettings: '-emailAddress $(toEmailAddress)'
              deploymentMethod: 'zipDeploy'
