trigger:
- main

pr: none

pool:
  vmImage: 'vs2017-win2016'

variables:
- template: variables/pipeline-vars.yml

jobs:
- job: logic_app_build
  displayName: 'Build and publish logic app'
  steps:
  - task: AzurePowerShell@4
    displayName: 'Generate connections.json file'
    inputs:
      azureSubscription: 'BeegalaInternalSubscription'
      ScriptType: 'FilePath'
      ScriptPath: '$(System.DefaultWorkingDirectory)/logicappsaa/.pipelines/scripts/Generate-Connections.ps1'
      ScriptArguments: '-resourceGroup $(resourceGroupName) -outputlocation $(System.DefaultWorkingDirectory)/logicappsaa/connections.json'
      FailOnStandardError: true
      azurePowerShellVersion: 'LatestVersion'
      pwsh: true

  - task: CopyFiles@2
    displayName: 'Create project folder'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/logicappsaa'
      Contents: |
        host.json
        proxies.json
        connections.json
        EmailWorkflow/**
      TargetFolder: 'project_output'

  - task: ArchiveFiles@2
    displayName: 'Create project zip'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/project_output'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish project zip artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: '$(logicAppCIArtifactName)'
      publishLocation: 'pipeline'
